repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.9.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-walrus==1.1.0]

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        name: isort (python)

-   repo: local
    hooks:
    -   id: export-requirements
        name: Convert pyproject.toml to requirements.txt
        language: system
        entry: poetry export --dev -f requirements.txt --without-hashes --output requirements.txt
        files: "^pyproject.toml$"
        pass_filenames: false