# Generated by Django 3.2.12 on 2022-04-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=40)),
                ('img_url', models.URLField()),
                ('media_info', models.CharField(max_length=40)),
                ('post_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=10)),
            ],
        ),
    ]
